### ISSUE TITLE
En el repositorio solo debe almacenarse código fuente

### ISSUE THREAD

**Issue by evolentini** [VictorBelaunde/TSE#1]
En el repositorio no se debe almacenar ni código binario ni archivos generados por herramientas automáticas, solo se debe almacenar código fuente. Por eso la carpeta `build` debe agregarse en el archivo `.gitignore` y eliminarse de repositorio.

Tambien se deben ignorar los archivos del sistema operativo como `.DS_Store`

@marianofino @rafaeloliva

**Comment by VictorBelaunde** [comment]
Resuelto.
https://github.com/VictorBelaunde/TSE/blob/0630a44391c1655074b4bd743a3789a3da0645d5/.gitignore#LL1C1-L1C1
