### ISSUE TITLE
Todas las funciones de la biblioteca deben tener un comportamiento uniforme

### ISSUE THREAD

**Issue by evolentini** [VictorBelaunde/TSE#2]
Si las funciones `leds_prende_uno()` y `leds_apaga_uno()` no reciben de nuevo la dirección del puerto, las funciones `leds_prende_todos()` y `leds_apaga_todos()` tampoco deben hacerlo.

https://github.com/VictorBelaunde/TSE/blob/bf2a5d43ea7c39a6ead4a6935d98e709a2ffb4ce/src/leds.c#L38-L48

@marianofino @rafaeloliva

**Comment by VictorBelaunde** [comment]
Resuelto.
https://github.com/VictorBelaunde/TSE/blob/0630a44391c1655074b4bd743a3789a3da0645d5/src/leds.c#L38
