### ISSUE TITLE
Se pueden refactorizar las pruebas para escribir menos (y hacerlas mas declarativas)

### ISSUE THREAD

**Issue by evolentini** [VictorBelaunde/TSE#4]
Se puede usar un `TEST_ASSERT()` directamente sobre el resultado de la función para evitar declarar la variable. De esta forma estas pruebas quedarían mas compactas. Por ejemplo esta prueba

https://github.com/VictorBelaunde/TSE/blob/bf2a5d43ea7c39a6ead4a6935d98e709a2ffb4ce/test/test_leds.c#L48-L54

podría quedar directamente como

```c
void test_prede_un_led_consulto_estado(void)
{
    leds_prende_uno(2);
    TEST_ASSERT_TRUE(leds_estado_led(2));
}
```

@marianofino @rafaeloliva

**Comment by VictorBelaunde** [comment]
Resuelto.
https://github.com/VictorBelaunde/TSE/blob/0630a44391c1655074b4bd743a3789a3da0645d5/test/test_leds.c#L48
