### ISSUE TITLE
No se aplicó correctamente la metodología

### ISSUE THREAD

**Issue by evolentini** [VictorBelaunde/TSE#5]
La metodología presentad pide que se escriba una prueba que falle antes de escribir cualquier código de producción. Esta prueba no puede haber fallado nunca porque no tiene ningún `TEST_ASSERT()`.

https://github.com/VictorBelaunde/TSE/blob/bf2a5d43ea7c39a6ead4a6935d98e709a2ffb4ce/test/test_leds.c#L56-L62

@marianofino @rafaeloliva

**Comment by VictorBelaunde** [comment]
Corregido!. Evidentemente se me pasó por alto el TEST_ASSERT porque igualmente la prueba daba PASED, incluso sin el ASSERT.
